version: 3

tasks:
  init:
    desc: initialise local environment
    cmds:
      - task: pre-commit:init

  pre-commit:init:
    desc: initialises pre-commit hooks
    cmds:
      - pre-commit install

  single:dev:
    cmds:
      - skaffold dev --port-forward --no-prune=false --cache-artifacts=false

  single:run:
    cmds:
      - skaffold run --port-forward --no-prune=false --cache-artifacts=false

  scaled:dev:
    cmds:
      - skaffold dev --port-forward --no-prune=false --cache-artifacts=false --profile=scaled

  cleanup:
    cmds:
      - skaffold delete
